### ISSUE TITLE
Working with PlatformIO

### ISSUE THREAD

**Issue by joe31093** [vanbergeijk/teensy-3.6-FreeRTOS-template#1]
Hello Jacob.  I am new to the Teensy3.6 and I am interested using your FreeRTOS port with PlatformIO in OS X.  I have a project created and incorporated your files.  I crated a FreeRTOS folder in the src directory and copied all the FreeRTOS files into the folder using a flat structure.  I used the portable/GCC/ARM_CM4_MPU port.c and portmacro.h files.  Not sure if this is correct set of files to use.

I managed to get it to compile but I am getting a few errors.  Do you see something that I am missing?  Thanks for the help.

Linking .pioenvs/teensy36/firmware.elf
.pioenvs/teensy36/src/FreeRTOS/port.o: In function `xPortStartScheduler':
/Users/joe/Documents/Source/Teensy36_FreeRTOS9/src/FreeRTOS/port.c:425: undefined reference to `__FLASH_segment_start__'
/Users/joe/Documents/Source/Teensy36_FreeRTOS9/src/FreeRTOS/port.c:425: undefined reference to `__FLASH_segment_end__'
/Users/joe/Documents/Source/Teensy36_FreeRTOS9/src/FreeRTOS/port.c:425: undefined reference to `__privileged_functions_end__'
/Users/joe/Documents/Source/Teensy36_FreeRTOS9/src/FreeRTOS/port.c:425: undefined reference to `__privileged_data_start__'
/Users/joe/Documents/Source/Teensy36_FreeRTOS9/src/FreeRTOS/port.c:425: undefined reference to `__privileged_data_end__'
.pioenvs/teensy36/src/FreeRTOS/port.o: In function `vPortStoreTaskMPUSettings':
/Users/joe/Documents/Source/Teensy36_FreeRTOS9/src/FreeRTOS/port.c:728: undefined reference to `__SRAM_segment_start__'
/Users/joe/Documents/Source/Teensy36_FreeRTOS9/src/FreeRTOS/port.c:728: undefined reference to `__SRAM_segment_end__'
/Users/joe/Documents/Source/Teensy36_FreeRTOS9/src/FreeRTOS/port.c:728: undefined reference to `__privileged_data_start__'
/Users/joe/Documents/Source/Teensy36_FreeRTOS9/src/FreeRTOS/port.c:728: undefined reference to `__privileged_data_end__'
collect2: error: ld returned 1 exit status
*** [.pioenvs/teensy36/firmware.elf] Error 1
========================== [ERROR] Took 15.46 seconds ==========================

**Comment by vanbergeijk** [comment]
Hello Joe,

I used the /ARM_CM4F/port.c and portmacro.h files for the Teensy 3.6. If you have a reason to stick to the CM4 port then the references you've described can be taken from the FLASH and RAM segments as defined in the mk66fx1m0.ld file located in the /teensy3 folder:

MEMORY
{
	FLASH (rx) : ORIGIN = 0x00000000, LENGTH = 1024K
	RAM  (rwx) : ORIGIN = 0x1FFF0000, LENGTH = 256K
}

**Comment by joe31093** [comment]
Great, thank you so much.  I appreciate you getting back to me.
